from . import res_partner
from . import product_template
from . import stock_picking
from . import sale_order
from . import account_tax
from . import mrp_bom
from . import mrp_bom_line
from . import production_externally_wizard
from . import stock_inventory
from . import stock_location
from . import omnia_mold_mold_configuration
from . import common
from . import stock_move
from . import account_fiscal_position
