{ 
    'name': "RDS Documents", 
    'summary': "Un modulo di RDS per gestire i documenti", 
    'description': """Questo modulo permette di archiviare documenti, gestire le copie fisiche, visualizzare i file nel browser.""", 
    'author': "RDS Moulding Technology SpA", 
    'license': "AGPL-3", 
    'website': "http://rdsmoulding.com", 
    'category': 'Documents', 
    'version': '11.0.1.0.0', 
    'depends': ['base','mail','crm','hr'], 
    'data': ['security/document_security.xml', 'security/ir.model.access.csv','views/views.xml','views/integrations.xml', 'views/web_asset_backend_template.xml'],
    'application': 'true',
    'installable': 'true',
    'qweb': ['static/src/xml/templates.xml', 'static/src/xml/thread.xml'],
}