{ 
    'name': "RDS HR Attendances Extension", 
    'summary': "Un modulo di RDS per migliorare la gestione presenze-assenze", 
    'description': """""", 
    'author': "RDS Moulding Technology SpA", 
    'license': "AGPL-3", 
    'website': "http://rdsmoulding.com", 
    'category': 'hr', 
    'version': '11.0.1.0.0', 
    'depends': ['hr', 'web_flaggrid'], 
    'data': ['views/hr_wu_views.xml',
             'wizard/payroll_printer_view.xml', 
             'controllers/kiosk.xml', 
             'views/web_asset_backend_template.xml', 
             'security/ir.model.access.csv',
             'report/payroll_report.xml'],
    'application': 'false',
    'installable': 'true',
} 